Repository TTG-Club/core-api, pull requests merged in 2024-11, with the labels that each got.

#26 Многочисленные изменение в логике Species
  pom.xml
  src/main/java/club/ttg/dnd5/controller/character/SpecieController.java
  src/main/java/club/ttg/dnd5/controller/species/SpeciesController.java
  src/main/java/club/ttg/dnd5/dto/base/BaseDTO.java
  src/main/java/club/ttg/dnd5/dto/base/DetailableDTO.java
  src/main/java/club/ttg/dnd5/dto/base/HasSourceDTO.java
  src/main/java/club/ttg/dnd5/dto/base/SourceDto.java
  src/main/java/club/ttg/dnd5/dto/base/SourceResponse.java
  src/main/java/club/ttg/dnd5/dto/character/ClassFeatureDto.java
  src/main/java/club/ttg/dnd5/dto/character/ClassRequest.java
  src/main/java/club/ttg/dnd5/dto/character/ClassResponse.java
  src/main/java/club/ttg/dnd5/dto/engine/SearchRequest.java
  src/main/java/club/ttg/dnd5/dto/species/CreateSpeciesDTO.java
  src/main/java/club/ttg/dnd5/dto/species/SpeciesFeatureResponse.java
  src/main/java/club/ttg/dnd5/dto/species/SpeciesResponse.java
  src/main/java/club/ttg/dnd5/mapper/species/SourceMapper.java
  src/main/java/club/ttg/dnd5/model/Source.java
  src/main/java/club/ttg/dnd5/model/base/FeatureBase.java
  src/main/java/club/ttg/dnd5/model/base/HasSourceEntity.java
  src/main/java/club/ttg/dnd5/model/base/HasTags.java
  src/main/java/club/ttg/dnd5/model/base/NamedEntity.java
  src/main/java/club/ttg/dnd5/model/bestiary/Beast.java
  src/main/java/club/ttg/dnd5/model/book/Book.java
  src/main/java/club/ttg/dnd5/model/book/Source.java
  src/main/java/club/ttg/dnd5/model/book/TypeBook.java
  src/main/java/club/ttg/dnd5/model/character/Background.java
  src/main/java/club/ttg/dnd5/model/character/ClassCharacter.java
  src/main/java/club/ttg/dnd5/model/character/ClassFeature.java
  src/main/java/club/ttg/dnd5/model/character/Feat.java
  src/main/java/club/ttg/dnd5/model/character/Spell.java
  src/main/java/club/ttg/dnd5/model/item/Armor.java
  src/main/java/club/ttg/dnd5/model/item/Equipment.java
  src/main/java/club/ttg/dnd5/model/item/MagicItem.java
  src/main/java/club/ttg/dnd5/model/item/Weapon.java
  src/main/java/club/ttg/dnd5/model/species/Species.java
  src/main/java/club/ttg/dnd5/model/species/SpeciesFeature.java
  src/main/java/club/ttg/dnd5/repository/SourceRepository.java
  src/main/java/club/ttg/dnd5/repository/SpeciesFeatureRepository.java
  src/main/java/club/ttg/dnd5/repository/SpeciesRepository.java
  src/main/java/club/ttg/dnd5/repository/book/BookRepository.java
  src/main/java/club/ttg/dnd5/service/SourceService.java
  src/main/java/club/ttg/dnd5/service/species/SpeciesService.java
  src/main/java/club/ttg/dnd5/spec/SpeciesSpecification.java
  src/main/java/club/ttg/dnd5/spec/SpecificationPart.java
  src/main/java/club/ttg/dnd5/spec/part/NameSpecificationPart.java
  src/main/java/club/ttg/dnd5/spec/part/SourceSpecificationPart.java
  src/main/java/club/ttg/dnd5/spec/part/SpecificationPart.java
  src/main/java/club/ttg/dnd5/spec/part/TagsSpecificationPart.java
  src/main/java/club/ttg/dnd5/utills/Converter.java
  src/main/java/club/ttg/dnd5/utills/species/SpeciesFeatureConverter.java
  src/main/resources/json/request/create_aasimar_request.json
  src/main/resources/json/response/response_create_aasimar.json
  src/main/resources/scripts/books.sql
  src/main/tests/club/ttg/dnd5/spec/SpeciesControllerTest.java
  src/main/tests/club/ttg/dnd5/utills/ConverterTest.java
Labels: enhancement

#27 Приведение в порядок SpeciesService
  src/main/java/club/ttg/dnd5/controller/species/SpeciesController.java
  src/main/java/club/ttg/dnd5/dto/base/SourceResponse.java
  src/main/java/club/ttg/dnd5/dto/species/CreateSpeciesDto.java
  src/main/java/club/ttg/dnd5/dto/species/CreaturePropertiesDto.java
  src/main/java/club/ttg/dnd5/dto/species/SpeciesDto.java
  src/main/java/club/ttg/dnd5/dto/species/SpeciesFeatureDto.java
  src/main/java/club/ttg/dnd5/model/base/NamedEntity.java
  src/main/java/club/ttg/dnd5/service/species/SpeciesService.java
  src/main/java/club/ttg/dnd5/utills/Converter.java
  src/main/java/club/ttg/dnd5/utills/species/SpeciesFeatureConverter.java
  src/main/tests/club/ttg/dnd5/spec/SpeciesControllerTest.java
  src/main/tests/club/ttg/dnd5/utills/ConverterTest.java
  src/main/tests/club/ttg/dnd5/utills/SpeciesFeatureConverterTest.java
Labels: documentation

#28 Добавление тестовых данных на Dev + раннер Скриптов
  src/main/java/club/ttg/dnd5/config/OpenApiConfig.java
  src/main/java/club/ttg/dnd5/config/SqlScriptRunner.java
  src/main/java/club/ttg/dnd5/controller/species/SpeciesController.java
  src/main/java/club/ttg/dnd5/service/species/SpeciesService.java
  src/main/resources/application.properties
  src/main/resources/scripts/books.sql
  src/main/resources/scripts/setup.sql
Labels: documentation

#29 Updated setup script & Json-s
  src/main/java/club/ttg/dnd5/service/species/SpeciesService.java
  src/main/resources/json/request/species/post/add_child_forest_gnome.json
  src/main/resources/json/request/species/post/add_child_rock_gnome_to_parent.json
  src/main/resources/json/request/species/post/create_aasimar_request.json
  src/main/resources/json/request/species/post/create_gnome_forest_child_request.json
  src/main/resources/json/request/species/post/create_gnome_parent_request.json
  src/main/resources/json/request/species/post/create_gnome_rock_child.json
  src/main/resources/scripts/setup.sql
Labels: documentation

#31 Hotfix/configuration
  src/main/resources/application.properties
Labels: bug

#33 Обновление ДТО
  src/main/java/club/ttg/dnd5/dictionary/beastiary/CreatureType.java
  src/main/java/club/ttg/dnd5/dto/base/BaseDTO.java
  src/main/java/club/ttg/dnd5/dto/base/DetailableDTO.java
  src/main/java/club/ttg/dnd5/dto/base/GroupStrategy.java
  src/main/java/club/ttg/dnd5/dto/base/HasNameResponse.java
  src/main/java/club/ttg/dnd5/dto/base/HasSourceDTO.java
  src/main/java/club/ttg/dnd5/dto/base/NameBasedDTO.java
  src/main/java/club/ttg/dnd5/dto/base/SourceResponse.java
  src/main/java/club/ttg/dnd5/dto/base/TagDto.java
  src/main/java/club/ttg/dnd5/dto/species/CreateSpeciesDto.java
  src/main/java/club/ttg/dnd5/dto/species/CreaturePropertiesDto.java
  src/main/java/club/ttg/dnd5/dto/species/LinkedSpeciesDto.java
  src/main/java/club/ttg/dnd5/dto/species/MovementAttributes.java
  src/main/java/club/ttg/dnd5/dto/species/SpeciesDto.java
  src/main/java/club/ttg/dnd5/dto/species/SpeciesFeatureDto.java
  src/main/java/club/ttg/dnd5/model/base/CreatureProperties.java
  src/main/java/club/ttg/dnd5/model/base/NamedEntity.java
  src/main/java/club/ttg/dnd5/model/species/Species.java
  src/main/java/club/ttg/dnd5/service/species/SpeciesService.java
  src/main/java/club/ttg/dnd5/utills/Converter.java
  src/main/java/club/ttg/dnd5/utills/species/SpeciesFeatureConverter.java
  src/main/resources/json/request/species/post/create_gnome_forest_child_request.json
  src/main/resources/json/request/species/post/create_gnome_parent_request.json
  src/main/resources/json/request/species/post/create_gnome_rock_child.json
  src/main/resources/scripts/setup.sql
  src/main/tests/club/ttg/dnd5/utills/ConverterTest.java
  src/main/tests/club/ttg/dnd5/utills/SpeciesFeatureConverterTest.java
Labels: bug

#36 Классы
  src/main/java/club/ttg/dnd5/controller/character/ClassController.java
  src/main/java/club/ttg/dnd5/dictionary/Ability.java
  src/main/java/club/ttg/dnd5/dto/character/ClassDto.java
  src/main/java/club/ttg/dnd5/dto/character/ClassFeatureDto.java
  src/main/java/club/ttg/dnd5/dto/character/ClassMasteryDto.java
  src/main/java/club/ttg/dnd5/dto/character/ClassRequest.java
  src/main/java/club/ttg/dnd5/dto/character/ClassResponse.java
  src/main/java/club/ttg/dnd5/model/character/ClassCharacter.java
  src/main/java/club/ttg/dnd5/model/character/ClassFeature.java
  src/main/java/club/ttg/dnd5/repository/character/ClassRepository.java
  src/main/java/club/ttg/dnd5/service/character/ClassService.java
  src/main/java/club/ttg/dnd5/service/character/ClassServiceImpl.java
  src/main/java/club/ttg/dnd5/utills/Converter.java
  src/main/java/club/ttg/dnd5/utills/character/ClassConverter.java
  src/main/java/club/ttg/dnd5/utills/character/ClassFeatureConverter.java
Labels: enhancement

#37 TTG-Club/core-api#4 Черты
  src/main/java/club/ttg/dnd5/controller/character/ClassController.java
  src/main/java/club/ttg/dnd5/controller/character/FeatController.java
  src/main/java/club/ttg/dnd5/controller/character/TraitController.java
  src/main/java/club/ttg/dnd5/controller/tools/dictionary/DirectoryController.java
  src/main/java/club/ttg/dnd5/dictionary/character/FeatCategory.java
  src/main/java/club/ttg/dnd5/dto/character/FeatDto.java
  src/main/java/club/ttg/dnd5/dto/character/TraitResponse.java
  src/main/java/club/ttg/dnd5/model/character/Feat.java
  src/main/java/club/ttg/dnd5/repository/character/FeatRepository.java
  src/main/java/club/ttg/dnd5/service/character/FeatService.java
  src/main/java/club/ttg/dnd5/service/character/FeatServiceImpl.java
  src/main/java/club/ttg/dnd5/utills/character/FeatConverter.java
Labels: enhancement

#41 Feauture/liquid base
  pom.xml
  src/main/java/club/ttg/dnd5/dto/character/FeatDto.java
  src/main/java/club/ttg/dnd5/model/character/ClassFeature.java
  src/main/java/club/ttg/dnd5/utills/Converter.java
  src/main/resources/application.properties
  src/main/resources/liquibase/changelog-master.yaml
  src/main/resources/liquibase/db/changelog/initial-changelog.yaml
  src/main/resources/liquibase/db/changelog/initial-inserts-species.yaml
  src/main/resources/liquibase/db/sql/insert-species-data.sql
Labels: enhancement
