Repository TTG-Club/core-api, pull requests merged in 2025-03, with the labels that each got.

#63 Чейнджлог для видов
  pom.xml
  src/main/java/club/ttg/dnd5/domain/book/model/Book.java
  src/main/java/club/ttg/dnd5/domain/book/repository/BookRepository.java
  src/main/java/club/ttg/dnd5/domain/book/service/BookService.java
  src/main/java/club/ttg/dnd5/domain/common/model/Tag.java
  src/main/java/club/ttg/dnd5/domain/species/model/Species.java
  src/main/java/club/ttg/dnd5/domain/species/model/SpeciesFeature.java
  src/main/java/club/ttg/dnd5/domain/species/model/SpeciesSize.java
  src/main/java/club/ttg/dnd5/domain/species/service/TagService.java
  src/main/resources/db/changelog/2025/03/02-add_species_table.yaml.yaml
Labels: enhancement

#67 Исправление контроллера книг
  src/main/java/club/ttg/dnd5/domain/book/rest/controller/BookController.java
  src/main/java/club/ttg/dnd5/domain/book/rest/mapper/BookMapper.java
  src/main/java/club/ttg/dnd5/domain/book/service/BookService.java
  src/main/java/club/ttg/dnd5/domain/common/rest/controller/DictionariesController.java
Labels: enhancement

#66 Feature/spells
  src/main/java/club/ttg/dnd5/domain/book/service/BookService.java
  src/main/java/club/ttg/dnd5/domain/common/rest/controller/DictionariesController.java
  src/main/java/club/ttg/dnd5/domain/common/rest/dto/BaseRequest.java
  src/main/java/club/ttg/dnd5/domain/common/rest/dto/ShortResponse.java
  src/main/java/club/ttg/dnd5/domain/common/rest/dto/select/BaseSelectOptionDto.java
  src/main/java/club/ttg/dnd5/domain/common/rest/dto/select/MeasurableSelectOptionDto.java
  src/main/java/club/ttg/dnd5/domain/common/rest/dto/select/SelectOptionDto.java
  src/main/java/club/ttg/dnd5/domain/common/service/DictionariesService.java
  src/main/java/club/ttg/dnd5/domain/species/service/SpeciesService.java
  src/main/java/club/ttg/dnd5/domain/spell/mapper/SpellAffiliationMapper.java
  src/main/java/club/ttg/dnd5/domain/spell/mapper/SpellComponentsMapper.java
  src/main/java/club/ttg/dnd5/domain/spell/mapper/SpellMapper.java
  src/main/java/club/ttg/dnd5/domain/spell/model/ComparisonOperator.java
  src/main/java/club/ttg/dnd5/domain/spell/model/DistanceUnit.java
  src/main/java/club/ttg/dnd5/domain/spell/model/MaterialComponent.java
  src/main/java/club/ttg/dnd5/domain/spell/model/Spell.java
  src/main/java/club/ttg/dnd5/domain/spell/model/SpellCastingTime.java
  src/main/java/club/ttg/dnd5/domain/spell/model/SpellComponents.java
  src/main/java/club/ttg/dnd5/domain/spell/model/SpellDistance.java
  src/main/java/club/ttg/dnd5/domain/spell/model/SpellDuration.java
  src/main/java/club/ttg/dnd5/domain/spell/model/SpellSchool.java
  src/main/java/club/ttg/dnd5/domain/spell/model/TimeUnit.java
  src/main/java/club/ttg/dnd5/domain/spell/model/enums/CastingUnit.java
  src/main/java/club/ttg/dnd5/domain/spell/model/enums/DistanceUnit.java
  src/main/java/club/ttg/dnd5/domain/spell/model/enums/DurationUnit.java
  src/main/java/club/ttg/dnd5/domain/spell/model/enums/MagicSchool.java
  src/main/java/club/ttg/dnd5/domain/spell/repository/SpellRepository.java
  src/main/java/club/ttg/dnd5/domain/spell/rest/controller/SpellController.java
  src/main/java/club/ttg/dnd5/domain/spell/rest/dto/SpellAffiliationDto.java
  src/main/java/club/ttg/dnd5/domain/spell/rest/dto/SpellAffiliationResponse.java
  src/main/java/club/ttg/dnd5/domain/spell/rest/dto/SpellDetailedComponents.java
  src/main/java/club/ttg/dnd5/domain/spell/rest/dto/SpellDetailedResponse.java
  src/main/java/club/ttg/dnd5/domain/spell/rest/dto/SpellRequest.java
  src/main/java/club/ttg/dnd5/domain/spell/rest/dto/SpellShortComponents.java
  src/main/java/club/ttg/dnd5/domain/spell/rest/dto/SpellShortResponse.java
  src/main/java/club/ttg/dnd5/domain/spell/rest/dto/create/CreateAffiliationRequest.java
  src/main/java/club/ttg/dnd5/domain/spell/rest/dto/create/SpellRequest.java
  src/main/java/club/ttg/dnd5/domain/spell/service/SpellService.java
  src/main/java/club/ttg/dnd5/domain/spell/service/SpellServiceImpl.java
  src/main/java/club/ttg/dnd5/dto/base/NumberFormatted.java
  src/main/java/club/ttg/dnd5/dto/base/mapping/BaseMapping.java
  src/main/resources/db/changelog/2025/03/05-01-init-spells.yaml
  src/main/resources/db/changelog/2025/03/05-02-update-spells.yaml
  src/main/resources/db/changelog/db.changelog-master.yaml
Labels: enhancement

#69 Update spells
  src/main/java/club/ttg/dnd5/domain/common/service/DictionariesService.java
  src/main/java/club/ttg/dnd5/domain/spell/mapper/SpellMapper.java
  src/main/java/club/ttg/dnd5/domain/spell/rest/controller/SpellController.java
  src/main/java/club/ttg/dnd5/domain/spell/service/SpellService.java
Labels: enhancement

#77 feature/species-searh-and-sort
  src/main/java/club/ttg/dnd5/domain/species/repository/SpeciesRepository.java
  src/main/java/club/ttg/dnd5/domain/species/rest/controller/SpeciesController.java
  src/main/java/club/ttg/dnd5/domain/species/service/SpeciesService.java
Labels: enhancement

#78 Начало пути
  pom.xml
  src/main/java/club/ttg/dnd5/domain/species/repository/SpeciesRepository.java
  src/main/java/club/ttg/dnd5/domain/species/rest/controller/SpeciesController.java
  src/main/java/club/ttg/dnd5/domain/species/rest/dto/SpeciesRequest.java
  src/main/java/club/ttg/dnd5/domain/species/service/SpeciesService.java
  src/main/java/club/ttg/dnd5/domain/spell/mapper/SpellMapper.java
  src/main/java/club/ttg/dnd5/domain/spell/model/Spell.java
  src/main/java/club/ttg/dnd5/domain/spell/model/SpellCastingTime.java
  src/main/java/club/ttg/dnd5/domain/spell/model/SpellDistance.java
  src/main/java/club/ttg/dnd5/domain/spell/model/SpellDuration.java
  src/main/java/club/ttg/dnd5/domain/spell/repository/SpellRepository.java
  src/main/java/club/ttg/dnd5/domain/spell/rest/controller/SpellController.java
  src/main/java/club/ttg/dnd5/domain/spell/rest/dto/SpellDetailedResponse.java
  src/main/java/club/ttg/dnd5/domain/spell/rest/dto/create/SpellRequest.java
  src/main/java/club/ttg/dnd5/domain/spell/service/SpellService.java
  src/main/java/club/ttg/dnd5/dto/base/NumberFormatted.java
  src/main/java/club/ttg/dnd5/util/SwitchLayoutUtils.java
  src/main/resources/db/changelog/2025/03/06-01-remove-concentration.yaml
  src/main/resources/db/changelog/db.changelog-master.yaml
Labels: release

#79 Сохранение имени пользователя при добавлении сущности
  src/main/java/club/ttg/dnd5/config/SecurityConfig.java
  src/main/java/club/ttg/dnd5/domain/common/model/Timestamped.java
  src/main/java/club/ttg/dnd5/security/AuditorAwareImpl.java
Labels: enhancement

#82 Увеличения размера поля upper в spell
  src/main/java/club/ttg/dnd5/domain/spell/model/Spell.java
  src/main/resources/db/changelog/2025/03/07-update-spell-upper-text.yaml
  src/main/resources/db/changelog/db.changelog-master.yaml
Labels: bug

#85 Капитализация не измеримых единиц измерения
  src/main/java/club/ttg/dnd5/domain/spell/model/SpellDuration.java
  src/main/java/club/ttg/dnd5/domain/spell/model/enums/CastingUnit.java
  src/main/java/club/ttg/dnd5/dto/base/NumberFormatted.java
Labels: bug

#87 фикс отображения галереи в видах
  src/main/java/club/ttg/dnd5/domain/species/model/Species.java
  src/main/java/club/ttg/dnd5/domain/species/rest/dto/SpeciesDetailResponse.java
  src/main/java/club/ttg/dnd5/domain/species/rest/mapper/SpeciesMapper.java
Labels: bug

#88 Эндпоинт для заполнения формы для редактирования заклинаний
  src/main/java/club/ttg/dnd5/domain/spell/rest/controller/SpellController.java
  src/main/java/club/ttg/dnd5/domain/spell/rest/mapper/SpellMapper.java
  src/main/java/club/ttg/dnd5/domain/spell/service/SpellService.java
Labels: enhancement

#94 Release
  CONTRIBUTING.md
  LICENSE.md
  README.md
  src/main/java/club/ttg/dnd5/domain/common/rest/dto/BaseRequest.java
  src/main/java/club/ttg/dnd5/domain/common/rest/dto/BaseResponse.java
  src/main/java/club/ttg/dnd5/domain/species/model/CreatureProperties.java
  src/main/java/club/ttg/dnd5/domain/species/model/Species.java
  src/main/java/club/ttg/dnd5/domain/species/rest/controller/SpeciesController.java
  src/main/java/club/ttg/dnd5/domain/species/rest/dto/MovementAttributes.java
  src/main/java/club/ttg/dnd5/domain/species/rest/dto/SpeciesDetailResponse.java
  src/main/java/club/ttg/dnd5/domain/species/rest/dto/SpeciesFeatureResponse.java
  src/main/java/club/ttg/dnd5/domain/species/rest/mapper/SpeciesMapper.java
  src/main/java/club/ttg/dnd5/domain/spell/rest/controller/SpellController.java
  src/main/java/club/ttg/dnd5/domain/spell/rest/dto/SpellDetailedResponse.java
  src/main/java/club/ttg/dnd5/domain/spell/rest/mapper/SpellMapper.java
  src/main/java/club/ttg/dnd5/domain/spell/service/SpellService.java
  src/main/java/club/ttg/dnd5/dto/base/deserializer/MarkupDescriptionDeserializer.java
  src/main/java/club/ttg/dnd5/dto/base/serializer/MarkupDescriptionSerializer.java
  src/main/resources/db/changelog/2025/03/17-01-add-markup-description.yaml
  src/main/resources/db/changelog/2025/03/19-01-delete-markup-description.yaml
  src/main/resources/db/changelog/2025/03/sql/update_markup_description_spells_and_species.sql
  src/main/resources/db/changelog/db.changelog-master.yaml
Labels: release

#95 Feature/glossary Глосарий
  src/main/java/club/ttg/dnd5/domain/glossary/controller/GlossaryController.java
  src/main/java/club/ttg/dnd5/domain/glossary/repository/GlossaryRepository.java
  src/main/java/club/ttg/dnd5/domain/glossary/rest/dto/GlossaryDetailedResponse.java
  src/main/java/club/ttg/dnd5/domain/glossary/rest/dto/GlossaryShortResponse.java
  src/main/java/club/ttg/dnd5/domain/glossary/rest/dto/create/GlossaryRequest.java
  src/main/java/club/ttg/dnd5/domain/glossary/rest/mapper/GlossaryMapper.java
  src/main/java/club/ttg/dnd5/domain/glossary/service/GlossaryService.java
  src/main/resources/db/changelog/2025/03/20-03-init-glossary.yaml
  src/main/resources/db/changelog/db.changelog-master.yaml
Labels: enhancement
